#!/usr/bin/env python3
"""Rebuild every wiki/<folder>/_index.md hub from the notes actually in that folder.

Hubs were static scaffold pages that never listed their notes, so most notes were unreachable
from the index. Run after adding notes: python build_hubs.py --vault <vault dir containing wiki/>
Notes under 700 characters with no real body are listed as unfilled templates, not knowledge.
"""
import argparse
import datetime
import pathlib
import re

STUB_CHARS = 700
SKIP = {"_index.md"}


def meta(text):
    fm = re.match(r"---\n(.*?)\n---", text, re.S)
    fields = dict(re.findall(r'^(\w+):\s*"?([^"\n]*)"?', fm.group(1), re.M)) if fm else {}
    body = text[fm.end():] if fm else text
    summary = ""
    for line in body.splitlines():
        line = line.strip()
        if line.startswith(">") and len(line) > 3:
            summary = line.lstrip("> ").strip()
            break
        if line and not line.startswith(("#", "!", "|", "-", "<")) and len(line) > 30:
            summary = line
            break
    summary = re.sub(r"\[\[([^\]|]+)\|?([^\]]*)\]\]", lambda m: m.group(2) or m.group(1), summary)
    summary = re.sub(r"[*`]", "", summary)
    return fields, (summary[:160] + "...") if len(summary) > 160 else summary


def build(vault, today):
    wiki = pathlib.Path(vault) / "wiki"
    written = []
    for folder in sorted(p for p in wiki.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))):
        notes = sorted(n for n in folder.iterdir() if n.suffix in (".md", ".canvas") and n.name not in SKIP)
        real, stubs = [], []
        for n in notes:
            text = n.read_text(encoding="utf-8", errors="replace")
            fields, summary = meta(text) if n.suffix == ".md" else ({}, "")
            link = n.name if n.suffix == ".canvas" else n.stem   # Obsidian needs the .canvas extension in the link
            entry = (fields.get("updated") or fields.get("created") or "", link, fields.get("title") or n.stem, summary)
            (stubs if len(text) < STUB_CHARS and n.suffix == ".md" else real).append(entry)
        newest_first = folder.name in ("reports",)
        real.sort(key=lambda e: (e[0], e[1]), reverse=newest_first)
        if not newest_first:
            real.sort(key=lambda e: e[1])
        title = folder.name.capitalize()
        lines = ["---", 'type: "hub"', f'title: "{title} Hub"', f'updated: "{today}"', 'status: "active"', "---", "",
                 f"# {title}", "", f"> Generated by `build_hubs.py` from the notes in `wiki/{folder.name}/`. Don't edit by hand; rerun it.", ""]
        if real:
            for date, stem, t, summary in real:
                label = f"[[{stem}|{t}]]" if t not in (stem, "") else (f"[[{stem}|{stem[:-7]}]]" if stem.endswith(".canvas") else f"[[{stem}]]")
                lines.append(f"- {label}" + (f" ({date})" if date and newest_first else "") + (f": {summary}" if summary else ""))
        else:
            lines.append("_No notes yet._")
        if stubs:
            lines += ["", "## Unfilled templates", "", "Scaffold pages that were never written. Fill them in or delete them; they hold no knowledge yet.", ""]
            lines += [f"- [[{stem}]]" for _, stem, _, _ in stubs]
        lines += ["", "Back to [[index]] · [[hot]]", ""]
        (folder / "_index.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
        written.append((folder.name, len(real), len(stubs)))
    return written


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vault", required=True)
    args = ap.parse_args()
    for name, n_real, n_stub in build(args.vault, datetime.date.today().isoformat()):
        print(f"{name:14s} {n_real:3d} notes, {n_stub:2d} unfilled templates")


if __name__ == "__main__":
    main()
